### ISSUE TITLE
HxD secure download

### ISSUE THREAD

**Issue by welwood08** [ComFreek/chocolatey-packages#3]
In case you weren't aware, the installer is available over a secure connection (the download page currently has a hard-coded HTTP link, but the server redirects every insecure connection to HTTPS). I only noticed because the FTP download in chocolatey failed for me, but that's probably just my environment. It looks like moving away from FTP might slightly simplify and standardise the latter half of the install script anyway.

**Comment by ComFreek** [comment]
> the server redirects every insecure connection to HTTPS

Indeed, I wasn't aware of this.

Thanks for reaching out to me! I am currently relatively busy, so it would take some days for me to fix and test it. If you would like to have a quicker update or are happy to help, I would accept a PR :)
