### ISSUE TITLE
Link to pympress package from pympress GitHub repo's README once pympress package is done

### ISSUE THREAD

**Issue by ComFreek** [ComFreek/chocolatey-packages#9]
Wait for Cimbali/pympress#109

**Comment by Cimbali** [comment]
Please ping me whenever the pympress package is available online (I suppose it will show in https://chocolatey.org/search?q=pympress ?) so that I can test it and point to it from the install instructions.

**Comment by ComFreek** [comment]
Yup, will do. Currently, it is still awaiting human moderation.

**Comment by ComFreek** [comment]
Tracked by Cimbali/pympress#112.
